### ISSUE TITLE
Security group blocks all traffic

### ISSUE THREAD

**Issue by johannesboyne** [azavea/terraform-aws-ecs-web-service#5]
Thanks for providing this terraform module!
I'm wondering how the following would work:
https://github.com/azavea/terraform-aws-ecs-web-service/blob/develop/main.tf#L4
The security group would not allow any traffic, thus the LB would not route anything, right?
Maybe I'm not seeing a certain part, but got a bit confused by that.

Cheers!

**Comment by hectcastro** [comment]
Hey @johannesboyne.

The security group is intentionally left empty so that users can associate rules with it via the `aws_security_group_rule` resource. An example of how we do that in practice can be found here: https://github.com/geotrellis/tree-prioritization-demo/blob/master/deployment/terraform/firewall.tf#L4-L12
